/* Enigme.java */
/* Generated By:JavaCC: Do not edit this line. Enigme.java */
import java.util.HashMap;

public class Enigme implements EnigmeConstants {
    private static HashMap<String, Integer> symbolTable = new HashMap<>();
    private static HashMap<String, String> symbolTableString = new HashMap<>();

    public static void main(String[] args) throws ParseException {
        System.out.println("Entrez un programme '\u00c9nigme' \u00e0 parser :");
        Enigme parser = new Enigme(System.in);
        parser.programme();
        System.out.println("Programme analys\u00e9 avec succ\u00e8s !");
    }

  static final public void programme() throws ParseException {
System.out.println("-> Entr\u00e9e dans programme");
    jj_consume_token(DEBUT);
    instructions();
    jj_consume_token(FIN);
System.out.println("<- Sortie de programme");
}

  static final public void instructions() throws ParseException {
System.out.println("-> Entr\u00e9e dans instructions");
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AFFICHERINT:
      case AFFICHERSTRING:
      case LIREINT:
      case LIRESTRING:
      case ENTIER:
      case CHAINE:
      case SI:
      case TANTQUE:
      case POUR:
      case IDENTIFIANT:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      instruction();
      jj_consume_token(SEMICOLON);
    }
System.out.println("<- Sortie de instructions");
}

  static final public void instruction() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case AFFICHERINT:{
      afficherInt();
      break;
      }
    case AFFICHERSTRING:{
      afficherString();
      break;
      }
    case LIREINT:{
      lireInt();
      break;
      }
    case LIRESTRING:{
      lireString();
      break;
      }
    case ENTIER:{
      declarationVariable();
      break;
      }
    case CHAINE:{
      declarationVariableString();
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      if (jj_2_1(3)) {
        affectation();
      } else if (jj_2_2(3)) {
        affectationString();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case SI:{
          condition();
          break;
          }
        case TANTQUE:{
          boucleTantQue();
          break;
          }
        case POUR:{
          bouclePour();
          break;
          }
        default:
          jj_la1[2] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
}

  static final public void declarationVariable() throws ParseException {
    jj_consume_token(ENTIER);
    jj_consume_token(IDENTIFIANT);
symbolTable.put(token.image, 0);
}

  static final public void declarationVariableString() throws ParseException {
    jj_consume_token(CHAINE);
    jj_consume_token(IDENTIFIANT);
symbolTableString.put(token.image, "");
}

  static final public void affectation() throws ParseException {String varName; int value;
    jj_consume_token(IDENTIFIANT);
varName = token.image;
    jj_consume_token(39);
    value = expression();
symbolTable.put(varName, value);
}

  static final public void affectationString() throws ParseException {String varName;
    jj_consume_token(IDENTIFIANT);
varName = token.image;
    jj_consume_token(39);
    jj_consume_token(STRING);
symbolTableString.put(token.image, token.image);
}

  static final public void afficherInt() throws ParseException {int value;
System.out.println("-> Entr\u00e9e dans afficherInt");
    jj_consume_token(AFFICHERINT);
    jj_consume_token(40);
    value = expression();
    jj_consume_token(41);
System.out.println("Afficher (Int) : " + value);
System.out.println("<- Sortie de afficherInt");
}

  static final public void afficherString() throws ParseException {String value;
System.out.println("-> Entr\u00e9e dans afficherString");
    jj_consume_token(AFFICHERSTRING);
    jj_consume_token(40);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STRING:{
      jj_consume_token(STRING);
value = token.image;
      break;
      }
    case IDENTIFIANT:{
      jj_consume_token(IDENTIFIANT);
if (symbolTableString.containsKey(token.image)) {
                    value = symbolTableString.get(token.image);
                } else {
                    {if (true) throw new Error("Variable non d\u00e9clar\u00e9e : " + token.image);}
                }
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(41);
System.out.println("Afficher (String) : " + value);
System.out.println("<- Sortie de afficherString");
}

  static final public void lireInt() throws ParseException {
System.out.println("-> Entr\u00e9e dans lireInt");
    jj_consume_token(LIREINT);
    jj_consume_token(40);
    jj_consume_token(IDENTIFIANT);
    jj_consume_token(41);
if (!symbolTable.containsKey(token.image)) {
            {if (true) throw new Error("Variable non d\u00e9clar\u00e9e : " + token.image);}
        }
        symbolTable.put(token.image, 42); // Exemple de valeur lue

System.out.println("<- Sortie de lireInt");
}

  static final public void lireString() throws ParseException {
System.out.println("-> Entr\u00e9e dans lireString");
    jj_consume_token(LIRESTRING);
    jj_consume_token(40);
    jj_consume_token(IDENTIFIANT);
    jj_consume_token(41);
if (!symbolTableString.containsKey(token.image)) {
            {if (true) throw new Error("Variable non d\u00e9clar\u00e9e : " + token.image);}
        }
        symbolTableString.put(token.image, "exemple"); // Exemple de valeur lue

System.out.println("<- Sortie de lireString");
}

  static final public void condition() throws ParseException {
System.out.println("-> Entr\u00e9e dans condition");
    jj_consume_token(SI);
    expBool();
    jj_consume_token(ALORS);
    instructions();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SINON:{
      jj_consume_token(SINON);
      instructions();
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      ;
    }
    jj_consume_token(FINSI);
System.out.println("<- Sortie de condition");
}

  static final public void boucleTantQue() throws ParseException {
System.out.println("-> Entr\u00e9e dans boucleTantQue");
    jj_consume_token(TANTQUE);
    expBool();
    jj_consume_token(FAIRE);
    instructions();
    jj_consume_token(FINTANTQUE);
System.out.println("<- Sortie de boucleTantQue");
}

  static final public void bouclePour() throws ParseException {
System.out.println("-> Entr\u00e9e dans bouclePour");
    jj_consume_token(POUR);
    jj_consume_token(IDENTIFIANT);
    jj_consume_token(DE);
    expArith();
    jj_consume_token(A);
    expArith();
    jj_consume_token(FAIRE);
    instructions();
    jj_consume_token(FINPOUR);
System.out.println("<- Sortie de bouclePour");
}

  static final public int expression() throws ParseException {int result;
    result = expArith();
{if ("" != null) return result;}
    throw new Error("Missing return statement in function");
}

  static final public int expArith() throws ParseException {int result; int term1, term2;
    term1 = term();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 42:
      case 43:{
        ;
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        break label_2;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 42:{
        jj_consume_token(42);
        term2 = term();
result = term1 + term2; term1 = result;
        break;
        }
      case 43:{
        jj_consume_token(43);
        term2 = term();
result = term1 - term2; term1 = result;
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return term1;}
    throw new Error("Missing return statement in function");
}

  static final public int term() throws ParseException {int result; int factor1, factor2;
    factor1 = factor();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 44:
      case 45:{
        ;
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        break label_3;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 44:{
        jj_consume_token(44);
        factor2 = factor();
result = factor1 * factor2; factor1 = result;
        break;
        }
      case 45:{
        jj_consume_token(45);
        factor2 = factor();
if (factor2 == 0) {if (true) throw new Error("Division par z\u00e9ro !");}
            result = factor1 / factor2;
            factor1 = result;
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return factor1;}
    throw new Error("Missing return statement in function");
}

  static final public int factor() throws ParseException {int result;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUMBER:{
      jj_consume_token(NUMBER);
result = Integer.parseInt(token.image); {if ("" != null) return result;}
      break;
      }
    case IDENTIFIANT:{
      jj_consume_token(IDENTIFIANT);
if (symbolTable.containsKey(token.image)) {
            result = symbolTable.get(token.image);
        } else {
            {if (true) throw new Error("Variable non d\u00e9clar\u00e9e : " + token.image);}
        }
        {if ("" != null) return result;}
      break;
      }
    case 40:{
      jj_consume_token(40);
      result = expArith();
      jj_consume_token(41);
{if ("" != null) return result;}
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public boolean expBool() throws ParseException {boolean result; boolean right;
    result = termBool();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 46:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_4;
      }
      jj_consume_token(46);
      right = termBool();
result = result || right;
    }
{if ("" != null) return result;}
    throw new Error("Missing return statement in function");
}

  static final public boolean termBool() throws ParseException {boolean result; boolean right;
    result = factorBool();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 47:{
        ;
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        break label_5;
      }
      jj_consume_token(47);
      right = factorBool();
result = result && right;
    }
{if ("" != null) return result;}
    throw new Error("Missing return statement in function");
}

  static final public boolean factorBool() throws ParseException {boolean result;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 48:{
      jj_consume_token(48);
      result = factorBool();
result = !result;
      break;
      }
    case TRUE:
    case FALSE:
    case IDENTIFIANT:
    case NUMBER:
    case 40:{
      result = elementBool();
result = elementBool();
{if ("" != null) return result;}
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public boolean valueBool() throws ParseException {boolean result;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TRUE:{
      jj_consume_token(TRUE);
result = true;
      break;
      }
    case FALSE:{
      jj_consume_token(FALSE);
result = false;
{if ("" != null) return result;}
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public boolean elementBool() throws ParseException {boolean result;
    if (jj_2_3(3)) {
      jj_consume_token(40);
      result = expBool();
      jj_consume_token(41);
{if ("" != null) return result;}
    } else if (jj_2_4(2)) {
      comparison();
result = comparison();
    } else if (jj_2_5(2)) {
      jj_consume_token(TRUE);
{if ("" != null) return true;}
    } else if (jj_2_6(2)) {
      jj_consume_token(FALSE);
{if ("" != null) return false;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public boolean comparison() throws ParseException {boolean result; int left, right;
    left = expression();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case GT:{
      jj_consume_token(GT);
      right = expression();
result = left > right;
      break;
      }
    case LT:{
      jj_consume_token(LT);
      right = expression();
result = left < right;
      break;
      }
    case GE:{
      jj_consume_token(GE);
      right = expression();
result = left >= right;
      break;
      }
    case LE:{
      jj_consume_token(LE);
      right = expression();
result = left <= right;
      break;
      }
    case EQ:{
      jj_consume_token(EQ);
      right = expression();
result = left == right;
      break;
      }
    case NE:{
      jj_consume_token(NE);
      right = expression();
result = left != right;
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return result;}
    throw new Error("Missing return statement in function");
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_3R_factor_270_7_32()
 {
    if (jj_scan_token(IDENTIFIANT)) return true;
    return false;
  }

  static private boolean jj_3R_factor_269_5_26()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_factor_269_5_31()) {
    jj_scanpos = xsp;
    if (jj_3R_factor_270_7_32()) {
    jj_scanpos = xsp;
    if (jj_3R_factor_278_7_33()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_factor_269_5_31()
 {
    if (jj_scan_token(NUMBER)) return true;
    return false;
  }

  static private boolean jj_3R_term_258_11_35()
 {
    if (jj_scan_token(45)) return true;
    return false;
  }

  static private boolean jj_3R_term_257_9_28()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_term_257_9_34()) {
    jj_scanpos = xsp;
    if (jj_3R_term_258_11_35()) return true;
    }
    return false;
  }

  static private boolean jj_3R_term_257_9_34()
 {
    if (jj_scan_token(44)) return true;
    return false;
  }

  static private boolean jj_3R_term_255_5_22()
 {
    if (jj_3R_factor_269_5_26()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_term_257_9_28()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_expArith_248_11_30()
 {
    if (jj_scan_token(43)) return true;
    return false;
  }

  static private boolean jj_3R_expArith_247_9_25()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_expArith_247_9_29()) {
    jj_scanpos = xsp;
    if (jj_3R_expArith_248_11_30()) return true;
    }
    return false;
  }

  static private boolean jj_3R_expArith_247_9_29()
 {
    if (jj_scan_token(42)) return true;
    return false;
  }

  static private boolean jj_3R_expArith_245_5_19()
 {
    if (jj_3R_term_255_5_22()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_expArith_247_9_25()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_comparison_331_11_18()
 {
    if (jj_scan_token(NE)) return true;
    return false;
  }

  static private boolean jj_3R_comparison_330_11_17()
 {
    if (jj_scan_token(EQ)) return true;
    return false;
  }

  static private boolean jj_3R_expression_240_5_10()
 {
    if (jj_3R_expArith_245_5_19()) return true;
    return false;
  }

  static private boolean jj_3R_comparison_329_11_16()
 {
    if (jj_scan_token(LE)) return true;
    return false;
  }

  static private boolean jj_3R_comparison_328_11_15()
 {
    if (jj_scan_token(GE)) return true;
    return false;
  }

  static private boolean jj_3R_comparison_327_11_14()
 {
    if (jj_scan_token(LT)) return true;
    return false;
  }

  static private boolean jj_3R_comparison_326_9_13()
 {
    if (jj_scan_token(GT)) return true;
    return false;
  }

  static private boolean jj_3R_comparison_324_5_9()
 {
    if (jj_3R_expression_240_5_10()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_comparison_326_9_13()) {
    jj_scanpos = xsp;
    if (jj_3R_comparison_327_11_14()) {
    jj_scanpos = xsp;
    if (jj_3R_comparison_328_11_15()) {
    jj_scanpos = xsp;
    if (jj_3R_comparison_329_11_16()) {
    jj_scanpos = xsp;
    if (jj_3R_comparison_330_11_17()) {
    jj_scanpos = xsp;
    if (jj_3R_comparison_331_11_18()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_6()
 {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  static private boolean jj_3_5()
 {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  static private boolean jj_3_4()
 {
    if (jj_3R_comparison_324_5_9()) return true;
    return false;
  }

  static private boolean jj_3R_affectationString_126_5_7()
 {
    if (jj_scan_token(IDENTIFIANT)) return true;
    if (jj_scan_token(39)) return true;
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  static private boolean jj_3_3()
 {
    if (jj_scan_token(40)) return true;
    if (jj_3R_expBool_283_5_8()) return true;
    if (jj_scan_token(41)) return true;
    return false;
  }

  static private boolean jj_3R_elementBool_315_5_27()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3_6()) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_affectation_118_5_6()
 {
    if (jj_scan_token(IDENTIFIANT)) return true;
    if (jj_scan_token(39)) return true;
    if (jj_3R_expression_240_5_10()) return true;
    return false;
  }

  static private boolean jj_3R_factorBool_302_7_24()
 {
    if (jj_3R_elementBool_315_5_27()) return true;
    return false;
  }

  static private boolean jj_3R_factorBool_301_5_20()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_factorBool_301_5_23()) {
    jj_scanpos = xsp;
    if (jj_3R_factorBool_302_7_24()) return true;
    }
    return false;
  }

  static private boolean jj_3R_factorBool_301_5_23()
 {
    if (jj_scan_token(48)) return true;
    if (jj_3R_factorBool_301_5_20()) return true;
    return false;
  }

  static private boolean jj_3R_termBool_294_9_21()
 {
    if (jj_scan_token(47)) return true;
    return false;
  }

  static private boolean jj_3R_termBool_292_5_11()
 {
    if (jj_3R_factorBool_301_5_20()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_termBool_294_9_21()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_expBool_285_9_12()
 {
    if (jj_scan_token(46)) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_3R_affectationString_126_5_7()) return true;
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_affectation_118_5_6()) return true;
    return false;
  }

  static private boolean jj_3R_expBool_283_5_8()
 {
    if (jj_3R_termBool_292_5_11()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_expBool_285_9_12()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_factor_278_7_33()
 {
    if (jj_scan_token(40)) return true;
    if (jj_3R_expArith_245_5_19()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public EnigmeTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[15];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x4123f80,0x1f80,0x122000,0x14000000,0x8000,0x0,0x0,0x0,0x0,0xc000000,0x0,0x0,0xf000000,0x3000000,0xc0000000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x0,0xc00,0xc00,0x3000,0x3000,0x100,0x4000,0x8000,0x10100,0x0,0xf,};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[6];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Enigme(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Enigme(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new EnigmeTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Enigme(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new EnigmeTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new EnigmeTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Enigme(EnigmeTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(EnigmeTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[49];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 15; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 49; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 6; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
