/* Enigme.java */
/* Generated By:JavaCC: Do not edit this line. Enigme.java */
import java.util.HashMap;

public class Enigme implements EnigmeConstants {
    private static HashMap<String, Integer> symbolTable = new HashMap<>();
    private static HashMap<String, String> symbolTableString = new HashMap<>();

    public static void main(String[] args) throws ParseException {
        System.out.println("Entrez un programme '\u00c9nigme' \u00e0 parser :");
        Enigme parser = new Enigme(System.in);
        parser.programme();
        System.out.println("Programme analys\u00e9 avec succ\u00e8s !");
    }

  static final public void programme() throws ParseException {
System.out.println("-> Entr\u00e9e dans programme");
    jj_consume_token(DEBUT);
    instructions();
    jj_consume_token(FIN);
System.out.println("<- Sortie de programme");
}

  static final public void instructions() throws ParseException {
System.out.println("-> Entr\u00e9e dans instructions");
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AFFICHERINT:
      case AFFICHERSTRING:
      case LIREINT:
      case LIRESTRING:
      case ENTIER:
      case SI:
      case TANTQUE:
      case POUR:
      case IDENTIFIANT:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      instruction();
      jj_consume_token(SEMICOLON);
    }
System.out.println("<- Sortie de instructions");
}

  static final public void instruction() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case AFFICHERINT:{
System.out.println("-> Entr\u00e9e dans instruction");
      afficherInt();
      break;
      }
    case AFFICHERSTRING:{
      afficherString();
      break;
      }
    case LIREINT:{
      lireInt();
      break;
      }
    case LIRESTRING:{
      lireString();
      break;
      }
    case ENTIER:{
      declarationVariable();
      break;
      }
    case IDENTIFIANT:{
      affectation();
      break;
      }
    case SI:{
      condition();
      break;
      }
    case TANTQUE:{
      boucleTantQue();
      break;
      }
    case POUR:{
      bouclePour();
System.out.println("<- Sortie de instruction");
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void declarationVariable() throws ParseException {
System.out.println("-> Entr\u00e9e dans declarationVariable");
    jj_consume_token(ENTIER);
    jj_consume_token(IDENTIFIANT);
symbolTable.put(token.image, 0);
System.out.println("<- Sortie de declarationVariable");
}

  static final public void affectation() throws ParseException {String varName; int value;
System.out.println("-> Entr\u00e9e dans affectation");
    jj_consume_token(IDENTIFIANT);
varName = token.image;
    jj_consume_token(36);
    value = expression();
symbolTable.put(varName, value);
        System.out.println("Affectation : " + varName + " <- " + value);
System.out.println("<- Sortie de affectation");
}

  static final public void afficherInt() throws ParseException {int value;
System.out.println("-> Entr\u00e9e dans afficherInt");
    jj_consume_token(AFFICHERINT);
    jj_consume_token(37);
    value = expression();
    jj_consume_token(38);
System.out.println("Afficher (Int) : " + value);
System.out.println("<- Sortie de afficherInt");
}

  static final public void afficherString() throws ParseException {
System.out.println("-> Entr\u00e9e dans afficherString");
    jj_consume_token(AFFICHERSTRING);
    jj_consume_token(37);
    jj_consume_token(STRING);
    jj_consume_token(38);
System.out.println("Afficher (String) : " + token.image);
System.out.println("<- Sortie de afficherString");
}

  static final public void lireInt() throws ParseException {
System.out.println("-> Entr\u00e9e dans lireInt");
    jj_consume_token(LIREINT);
    jj_consume_token(37);
    jj_consume_token(IDENTIFIANT);
    jj_consume_token(38);
if (!symbolTable.containsKey(token.image)) {
            {if (true) throw new Error("Variable non d\u00e9clar\u00e9e : " + token.image);}
        }
        symbolTable.put(token.image, 42);
System.out.println("<- Sortie de lireInt");
}

  static final public void lireString() throws ParseException {
System.out.println("-> Entr\u00e9e dans lireString");
    jj_consume_token(LIRESTRING);
    jj_consume_token(37);
    jj_consume_token(IDENTIFIANT);
    jj_consume_token(38);
if (!symbolTableString.containsKey(token.image)) {
            {if (true) throw new Error("Variable non d\u00e9clar\u00e9e : " + token.image);}
        }
        symbolTableString.put(token.image, "exemple");
System.out.println("<- Sortie de lireString");
}

  static final public void condition() throws ParseException {
System.out.println("-> Entr\u00e9e dans condition");
    jj_consume_token(SI);
    comparisonExpression();
    jj_consume_token(ALORS);
    instructions();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SINON:{
      jj_consume_token(SINON);
      instructions();
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    jj_consume_token(FINSI);
System.out.println("<- Sortie de condition");
}

  static final public void boucleTantQue() throws ParseException {
System.out.println("-> Entr\u00e9e dans boucleTantQue");
    jj_consume_token(TANTQUE);
    comparisonExpression();
    jj_consume_token(FAIRE);
    instructions();
    jj_consume_token(FINTANTQUE);
System.out.println("<- Sortie de boucleTantQue");
}

  static final public void bouclePour() throws ParseException {
System.out.println("-> Entr\u00e9e dans bouclePour");
    jj_consume_token(POUR);
    jj_consume_token(IDENTIFIANT);
    jj_consume_token(DE);
    expression();
    jj_consume_token(A);
    expression();
    jj_consume_token(FAIRE);
    instructions();
    jj_consume_token(FINPOUR);
System.out.println("<- Sortie de bouclePour");
}

  static final public int expression() throws ParseException {int result;
System.out.println("-> Entr\u00e9e dans expression");
    result = simpleExpression();
{if ("" != null) return result;}
System.out.println("<- Sortie de expression");
    throw new Error("Missing return statement in function");
}

  static final public int simpleExpression() throws ParseException {int result = 0;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUMBER:{
System.out.println("-> Entr\u00e9e dans simpleExpression");
      jj_consume_token(NUMBER);
result = Integer.parseInt(token.image); {if ("" != null) return result;}
      break;
      }
    case IDENTIFIANT:{
      jj_consume_token(IDENTIFIANT);
if (symbolTable.containsKey(token.image)) {
            result = symbolTable.get(token.image);
        } else {
            {if (true) throw new Error("Variable non d\u00e9clar\u00e9e : " + token.image);}
        }
        {if ("" != null) return result;}
      break;
      }
    case 37:{
      jj_consume_token(37);
      expression();
      jj_consume_token(38);
result = expression(); {if ("" != null) return result;}
System.out.println("<- Sortie de simpleExpression");
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public boolean comparisonExpression() throws ParseException {boolean result = false; int left; int right;
    left = simpleExpression();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case EQUAL:
    case NEQUAL:
    case LESS:
    case LESSEQ:
    case GREATER:
    case GREATEREQ:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQUAL:{
        jj_consume_token(EQUAL);
        right = simpleExpression();
result = (left == right);
        break;
        }
      case NEQUAL:{
        jj_consume_token(NEQUAL);
        right = simpleExpression();
result = (left != right);
        break;
        }
      case LESS:{
        jj_consume_token(LESS);
        right = simpleExpression();
result = (left < right);
        break;
        }
      case LESSEQ:{
        jj_consume_token(LESSEQ);
        right = simpleExpression();
result = (left <= right);
        break;
        }
      case GREATER:{
        jj_consume_token(GREATER);
        right = simpleExpression();
result = (left > right);
        break;
        }
      case GREATEREQ:{
        jj_consume_token(GREATEREQ);
        right = simpleExpression();
result = (left >= right);
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
{if ("" != null) return result;}
    throw new Error("Missing return statement in function");
}

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public EnigmeTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[6];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x20091f80,0x20091f80,0x4000,0x60000000,0x1f800000,0x1f800000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x0,0x20,0x0,0x0,};
	}

  /** Constructor with InputStream. */
  public Enigme(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Enigme(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new EnigmeTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 6; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 6; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Enigme(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new EnigmeTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 6; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new EnigmeTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 6; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Enigme(EnigmeTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 6; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(EnigmeTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 6; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[39];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 6; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 39; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
