/* Generated By:JavaCC: Do not edit this line. EnigmeConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EnigmeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DEBUT = 5;
  /** RegularExpression Id. */
  int FIN = 6;
  /** RegularExpression Id. */
  int AFFICHERINT = 7;
  /** RegularExpression Id. */
  int AFFICHERSTRING = 8;
  /** RegularExpression Id. */
  int LIREINT = 9;
  /** RegularExpression Id. */
  int LIRESTRING = 10;
  /** RegularExpression Id. */
  int ENTIER = 11;
  /** RegularExpression Id. */
  int SI = 12;
  /** RegularExpression Id. */
  int ALORS = 13;
  /** RegularExpression Id. */
  int SINON = 14;
  /** RegularExpression Id. */
  int FINSI = 15;
  /** RegularExpression Id. */
  int TANTQUE = 16;
  /** RegularExpression Id. */
  int FAIRE = 17;
  /** RegularExpression Id. */
  int FINTANTQUE = 18;
  /** RegularExpression Id. */
  int POUR = 19;
  /** RegularExpression Id. */
  int DE = 20;
  /** RegularExpression Id. */
  int A = 21;
  /** RegularExpression Id. */
  int FINPOUR = 22;
  /** RegularExpression Id. */
  int EQUAL = 23;
  /** RegularExpression Id. */
  int NEQUAL = 24;
  /** RegularExpression Id. */
  int LESS = 25;
  /** RegularExpression Id. */
  int LESSEQ = 26;
  /** RegularExpression Id. */
  int GREATER = 27;
  /** RegularExpression Id. */
  int GREATEREQ = 28;
  /** RegularExpression Id. */
  int IDENTIFIANT = 29;
  /** RegularExpression Id. */
  int NUMBER = 30;
  /** RegularExpression Id. */
  int STRING = 31;
  /** RegularExpression Id. */
  int COMMENT = 32;
  /** RegularExpression Id. */
  int SEMICOLON = 33;
  /** RegularExpression Id. */
  int LETTER = 34;
  /** RegularExpression Id. */
  int DIGIT = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"d\\u00e9but\"",
    "\"fin\"",
    "\"afficherInt\"",
    "\"afficherString\"",
    "\"lireInt\"",
    "\"lireString\"",
    "\"entier\"",
    "\"si\"",
    "\"alors\"",
    "\"sinon\"",
    "\"finSi\"",
    "\"tantQue\"",
    "\"faire\"",
    "\"finTantQue\"",
    "\"pour\"",
    "\"de\"",
    "\"\\u00e0\"",
    "\"finPour\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "<IDENTIFIANT>",
    "<NUMBER>",
    "<STRING>",
    "<COMMENT>",
    "\";\"",
    "<LETTER>",
    "<DIGIT>",
    "\"<-\"",
    "\"(\"",
    "\")\"",
  };

}
