/* Generated By:JavaCC: Do not edit this line. EnigmeConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EnigmeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DEBUT = 5;
  /** RegularExpression Id. */
  int FIN = 6;
  /** RegularExpression Id. */
  int AFFICHERINT = 7;
  /** RegularExpression Id. */
  int AFFICHERSTRING = 8;
  /** RegularExpression Id. */
  int LIREINT = 9;
  /** RegularExpression Id. */
  int LIRESTRING = 10;
  /** RegularExpression Id. */
  int ENTIER = 11;
  /** RegularExpression Id. */
  int CHAINE = 12;
  /** RegularExpression Id. */
  int SI = 13;
  /** RegularExpression Id. */
  int ALORS = 14;
  /** RegularExpression Id. */
  int SINON = 15;
  /** RegularExpression Id. */
  int FINSI = 16;
  /** RegularExpression Id. */
  int TANTQUE = 17;
  /** RegularExpression Id. */
  int FAIRE = 18;
  /** RegularExpression Id. */
  int FINTANTQUE = 19;
  /** RegularExpression Id. */
  int POUR = 20;
  /** RegularExpression Id. */
  int DE = 21;
  /** RegularExpression Id. */
  int A = 22;
  /** RegularExpression Id. */
  int FINPOUR = 23;
  /** RegularExpression Id. */
  int IDENTIFIANT = 24;
  /** RegularExpression Id. */
  int NUMBER = 25;
  /** RegularExpression Id. */
  int STRING = 26;
  /** RegularExpression Id. */
  int COMMENT = 27;
  /** RegularExpression Id. */
  int TRUE = 28;
  /** RegularExpression Id. */
  int FALSE = 29;
  /** RegularExpression Id. */
  int GT = 30;
  /** RegularExpression Id. */
  int LT = 31;
  /** RegularExpression Id. */
  int GE = 32;
  /** RegularExpression Id. */
  int LE = 33;
  /** RegularExpression Id. */
  int EQ = 34;
  /** RegularExpression Id. */
  int NE = 35;
  /** RegularExpression Id. */
  int SEMICOLON = 36;
  /** RegularExpression Id. */
  int LETTER = 37;
  /** RegularExpression Id. */
  int DIGIT = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"d\\u00e9but\"",
    "\"fin\"",
    "\"afficherInt\"",
    "\"afficherString\"",
    "\"lireInt\"",
    "\"lireString\"",
    "\"entier\"",
    "\"chaine\"",
    "\"si\"",
    "\"alors\"",
    "\"sinon\"",
    "\"finSi\"",
    "\"tantQue\"",
    "\"faire\"",
    "\"finTantQue\"",
    "\"pour\"",
    "\"de\"",
    "\"\\u00e0\"",
    "\"finPour\"",
    "<IDENTIFIANT>",
    "<NUMBER>",
    "<STRING>",
    "<COMMENT>",
    "\"true\"",
    "\"false\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\";\"",
    "<LETTER>",
    "<DIGIT>",
    "\"<-\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
  };

}
